config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

app_name = 'portfolio'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path
from . import views

app_name = 'portfolio'

urlpatterns = [
    path('', views.home_view),
    path('Home', views.home_view, name='home'),
    path('Blog', views.blog_view, name='blog'),
    path('quizz', views.quizz_view, name='quizz'),
    path('novoPost', views.novoPost_view, name='novoPost'),
    path('editarPost/<int:post_id>', views.editarPost_view, name='editarPost'),
    path('apagarPost/<int:post_id>', views.apagarPost_view, name='apagarPost'),
    path('Apresentacao', views.apresentacao_view, name='apresentacao'),
    path('licenciatura', views.licenciatura_view, name='licenciatura'),
    path('projetos', views.projetos_view, name='projetos'),
    path('competencias', views.competencias_view, name='competencias'),
    path('formacao', views.formacao_view, name='formacao'),
    path('login', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

portfolio/models.py
from django.db import models


# Create your models here.
from portfolio.views import resolution_path


class Post(models.Model):
    autor = models.CharField(max_length=25)
    data = models.DateField(auto_now_add=True)
    titulo = models.CharField(max_length=30)
    descricao = models.TextField()

    def __str__(self):
        return f"{self.titulo}, {self.autor} - {self.data}"


class PontuacaoQuizz(models.Model):
    nome = models.CharField(max_length=25)
    pontuacao = models.IntegerField(default=0)

    def __str__(self):
        return self.nome


class Pessoa(models.Model):
    fotografia = models.ImageField(upload_to=resolution_path)

portfolio/forms.py
from django.forms import ModelForm
from django import forms
from .models import Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

        # ferramentas
        widgets = {
            'autor': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Autor do Post'}),

            'titulo': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Título do Post'}),
        }

portfolio/views.py
import base64
import datetime
import io
import urllib

import matplotlib
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from matplotlib import pyplot as plt

from .forms import PostForm
from .models import Post, PontuacaoQuizz

matplotlib.use('Agg')


def home_view(request):
    hoje = datetime.date.today()
    nasc = datetime.date(1998, 7, 7)
    anos = (hoje - nasc).days // 365

    context = {
        'anos': anos
    }
    return render(request, 'portfolio/home.html', context)


def apresentacao_view(request):
    return render(request, 'portfolio/apresentacao.html')


def blog_view(request):
    context = {'posts': Post.objects.all()}
    return render(request, 'portfolio/blog.html', context)


def licenciatura_view(request):
    return render(request, 'portfolio/licenciatura.html')


def competencias_view(request):
    return render(request, 'portfolio/competencias.html')


def projetos_view(request):
    return render(request, 'portfolio/projetos.html')


def formacao_view(request):
    return render(request, 'portfolio/formacao.html')


def login_view(request):

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(
            request,
            username=username,
            password=password)

        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('portfolio:home'))
        else:
            return render(request, 'portfolio/login.html', {
                'message': 'Credenciais inválidas.'
            })

    return render(request, 'portfolio/login.html')


def logout_view(request):
    logout(request)

    return render(request, 'portfolio/login.html', {
                'message': 'Obrigado pela visita!'
            })


def novoPost_view(request):
    form = PostForm(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:blog'))

    context = {
        'form': form
    }

    return render(request, 'portfolio/novoPost.html', context)


def editarPost_view(request, post_id):
    post = Post.objects.get(pk=post_id)
    form = PostForm(request.POST or None, instance=post)

    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:blog'))

    context = {'form': form, 'post_id': post_id}
    return render(request, 'portfolio/editarPost.html', context)


def apagarPost_view(request, post_id):
    Post.objects.get(pk=post_id).delete()
    return HttpResponseRedirect(reverse('portfolio:blog'))


def pontuacao_quizz(request):
    score = 0
    if request.POST['p1'] == 'javascript':
        score += 1

    if request.POST['p2'] == 'Elementos_Semanticos':
        score += 1

    if request.POST['p3'] == 'TopRightBotLeft':
        score += 1

    if request.POST['p4'] == 'def_Function':
        score += 1

    if request.POST['p5'] == 'conf_url_view_html':
        score += 1

    return score


def quizz_view(request):
    if request.method == 'POST':
        n = request.POST['nome']
        p = pontuacao_quizz(request)
        r = PontuacaoQuizz(nome=n, pontuacao=p)
        r.save()

    desenha_grafico_resultados(request)
    return render(request, 'portfolio/quizz.html')


def desenha_grafico_resultados(request):
    pontuacoes = PontuacaoQuizz.objects.all()
    pontuacao_sorted = sorted(pontuacoes, key=lambda objeto: objeto.pontuacao, reverse=False)
    lista_nomes = []
    lista_pontuacao = []

    for person in pontuacao_sorted:
        lista_nomes.append(person.nome)
        lista_pontuacao.append(person.pontuacao)

    plt.barh(lista_nomes, lista_pontuacao)
    plt.savefig('portfolio/static/portfolio/images/graf.png', bbox_inches='tight')

portfolio/templates/portfolio/apresentacao.html
{% extends 'portfolio/layout.html' %}

{% block main %}
	<h3>Apresentação</h3>
    <br>
    <p>
        Tenho 23 anos e tirei o curso em Gestão e Programação de Sistemas Informáticos na escola secundária da Amadora, juntamente com um estágio final de curso na empresa HBPro.
    </p>
    <p>
        Neste momento sou estudante universitário a tirar a Licenciatura em Engenharia Informática na Universidade Lusófona em Lisboa.
    </p>
    <p>
        Adoro programar, andar de mota, ouvir música e procuro sempre saber mais na área de informática ao qual sempre tive uma relação bastante próxima desde pequeno.
    </p>
    <p>
        Sou uma pessoa descontraída e que está sempre disponível para ajudar os outros.
    </p>
{% endblock %}

portfolio/templates/portfolio/blog.html
{% extends 'portfolio/layout.html' %}

{% block main %}
	<h3>Blog</h3>
    <a href="{% url 'portfolio:novoPost' %}" class="newPostBegin">
        <button class="buttonNewPostBegin">
            New Post (+)
        </button>
    </a>

    <div class = "posts">
        {% for post in posts %}
            <div class = "post">
                <!--<p>
                    {{ post.titulo }} : {{ post.autor }} - {{ post.data }}
                    <br> {{ post.descricao }}
                </p>-->
                <h2 class = "tituloPost">
                    {{ post.titulo }}
                </h2>
                <p class = "descPost">
                    {{ post.descricao }}
                </p>
                <p class = "dataPost">
                    {{ post.data.day }}/{{ post.data.month }}/{{ post.data.year }}
                </p>
                <p class = "autorPost">
                    {{ post.autor }} -
                </p>
                <div class = "managePost">
                    <u><a href="{% url 'portfolio:editarPost' post.id %}">Edit</a></u>
                    <u><a href="{% url 'portfolio:apagarPost' post.id %}">Delete</a></u>
                </div>
            </div>
        {% endfor %}
            <a href="{% url 'portfolio:novoPost' %}" class="newPostEnd">
                <button class="buttonNewPostEnd">
                    New Post (+)
                </button>
            </a>
    </div>
{% endblock %}

portfolio/templates/portfolio/competencias.html
{% extends 'portfolio/layout.html' %}

{% block main %}
	<h3>Competências</h3>
    <br>
    <h4>Linguagens de Programação:</h4>
    <br>
    <ul>
        <li>
            Java
        </li>
        <li>
            C#
        </li>
        <li>
            C
        </li>
        <li>
            Kotlin
        </li>
        <li>
            Python
        </li>
        <li>
            SQL
        </li>
        <li>
            Pascal
        </li>
        <li>
            HTML/CSS
        </li>
    </ul>
    <br><br>
    <h4>Tecnologias:</h4>
    <br>
    <ul>
        <li>
            Windows
        </li>
        <li>
            Linux
        </li>
        <li>
            Arduino
        </li>
        <li>
            WAMP
        </li>
        <li>
            Django
        </li>
        <li>
            Pascal
        </li>
        <li>
            HTML/CSS
        </li>
    </ul>
{% endblock %}

portfolio/templates/portfolio/editarPost.html
{% extends 'portfolio/layout.html' %}

{% block main %}
    <style>
        p{
            padding: 5px;
        }

        label{
            display: flex;
        }
    </style>
	<h3>NovoPost</h3>
    <br>
    <form action="{% url 'portfolio:editarPost' post_id %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <a href="{% url 'portfolio:blog' %}" role="button" class="btn btn-warning">Cancelar</a>
        <input type="submit" value="Gravar">
    </form>

{% endblock %}

portfolio/templates/portfolio/formacao.html
{% extends 'portfolio/layout.html' %}

{% block main %}
	<h3>Formação</h3>
    <br>
    <p>2015 - 2018: Curso de Gestão e Programação Informática - Média 17 - Escola Secundária da Amadora</p>
    <br>
    <p>2018 - 2018: Estágio de 3 meses na empresa HBPro</p>
    <br>
    <p>2020 - Atual: Licenciatura em Engenharia Informática - ULHT</p>
{% endblock %}

portfolio/templates/portfolio/home.html
{% extends 'portfolio/layout.html' %}

{% block main %}
    <style>
        main{
          padding: 0;
        }
    </style>
    <section>
        {% load static %}
        <video src="{% static 'portfolio/images/hero.mp4' %}" muted autoplay loop></video>
        <div class = "escuro"></div>
        <div class = "perfil-image">
            {% load static %}
            <img src="{% static 'portfolio/images/perfil.png' %}" alt="perfil">
            <p>
                Olá! Chamo-me João Yp, tenho {{ anos }} anos e sou estudante de Engenharia Informática na Universidade Lusófona em Lisboa!
            </p>
        </div>
    </section>


{% endblock %}

portfolio/templates/portfolio/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Laboratório 10 - Portfólio</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'portfolio/css/layout.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/css/home.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/css/blog.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/css/quizz.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/css/login.css' %}">
    <style>
        body{
            {% load static %}
            background-image: url("{% static 'portfolio/images/background.jpg' %}");
            background-repeat: no-repeat;
            background-position: center;
            background-size: cover;
            background-attachment: fixed;
        }
    </style>
</head>
<body>
  <header>
    <div>
        João Yp
    </div>
    <nav>
        <a href="{% url 'portfolio:home' %}">Home</a>
        <a href="{% url 'portfolio:apresentacao' %}">Apresentação</a>
        <a href="{% url 'portfolio:blog' %}">Blog</a>
        <a href="{% url 'portfolio:quizz' %}">Quizz</a>
        <a href="{% url 'portfolio:licenciatura' %}">Licenciatura</a>
        <a href="{% url 'portfolio:projetos' %}">Projetos</a>
        <a href="{% url 'portfolio:competencias' %}">Competências</a>
        <a href="{% url 'portfolio:formacao' %}">Formação</a>
    </nav>
      {% if request.user.is_authenticated %}
          <button class="login-user"><a href="{% url 'portfolio:logout' %}">Logout</a></button>
      {% else %}
          <button class="login-user"><a href="{% url 'portfolio:login' %}">Login</a></button>
      {% endif %}
  </header>
  <main>
      {% block main %}

      {% endblock main %}
  </main>
  <footer>
      <p>Contacto:</p>
      <u><a href="https://mail.google.com/mail/u/0/?view=cm&fs=1&to=joaomayp@gmail.com&su=&body=&tf=1" target="_blank">joaomayp@gmail.com</a></u>
      - ULHT, 2022
  </footer>
</body>
</html>

portfolio/templates/portfolio/licenciatura.html
{% extends 'portfolio/layout.html' %}

{% block main %}
    <h1>Listagem de 3 cadeiras de Eng. Informática:</h1>

    <div class="container">
      <div>
        <h2>Algoritmia e Estruturas de Dados</h2>
          <br>
          <p>
              - Cadeira de programação em Java no 2º Semestre no 1º ano no curso
              de Engenharia Informática.
          </p>
          <br>
          <p>
              - Esta cadeira ensina a manipular as várias estruturas de dados com uma
              programação orientada a objetos.
              <br><br>
              <b>
                 5.0 ECTS
              </b>
              <br><br>
          </p>
          {% load static %}
          <img src="{% static 'portfolio/images/5stars.png' %}" alt="5stars"
               style="margin-left: 25px; margin-top: 27px">
      </div>
      <div>
        <h2>Computação Gráfica</h2>
          <br>
          <p>
              - Cadeira de programação e manipulação de imagens em C# do 2º Semestre
              no 2º ano no curso de Engenharia Informática.
          </p>
          <br>
          <p>
              - Esta cadeira ensina a manipular imagens através de vários
              algoritmos matemáticos.
              <br><br>
              <b>
                  5.0 ECTS
              </b>
          </p>
          <br>
          {% load static %}
          <img src="{% static 'portfolio/images/5stars.png' %}" alt="5stars"
               style="margin-left: 25px; margin-top: 55px">
      </div>

      <div>
        <h2>Arquitetura Avançada de Computadores</h2>
          <br>
          <p>
              - Cadeira focada em hardware e Arduino no 1º Semestre no 2º ano no curso
              de Engenharia Informática.
          </p>
          <br>
          <p>
              - Esta cadeira ensina sobre o que acontece ao certo dentro um computador
              e Arduino com base na linguagem C++.
              <br><br>
              <b>
                  5.0 ECTS
              </b>
              <br><br>
          </p>
          {% load static %}
          <img src="{% static 'portfolio/images/4stars.png' %}" alt="5stars"
               style="margin-left: 25px; margin-top: 10px">
      </div>
    </div>

{% endblock %}

portfolio/templates/portfolio/login.html
{% extends 'portfolio/layout.html' %}

{% block main %}
	<h3 style="text-align: center">Login</h3>

    <form action="{% url 'portfolio:login' %}" method="post" class="formLogin">
        {% csrf_token %}
        <p>Username: <input type="text" name="username" placeholder="" class='form-control'></p>
        <p>Password: <input type="password" name="password" placeholder="" class='form-control'></p>
        <div class="msg-erro">
            {% if message %}
              <div> {{ message }} </div>
            {% endif %}
        </div>
        <div>
          <input type="submit" value="Login">
        </div>
    </form>
{% endblock %}

portfolio/templates/portfolio/novoPost.html
{% extends 'portfolio/layout.html' %}

{% block main %}
    <style>
        p{
            padding: 5px;
        }

        label{
            display: flex;
        }
    </style>
	<h3>Novo Post</h3>
    <br>
    <form method="POST" action="">
        {% csrf_token %}

        {{ form.as_p }}
        <input type="submit" value="Gravar">
    </form>

{% endblock %}

portfolio/templates/portfolio/projetos.html
{% extends 'portfolio/layout.html' %}

{% block main %}
    <h1>Projetos:</h1>

    <div class="projetos">
      <div style="text-align: center">
        <h2>Line Follower Robot</h2>
          <br>
          <p>
              Line Follower Robot foi um projeto para demonstração aos alunos da
              Escola Secundária da Amadora. Este projeto, desde o brainstorm da montagem
              (para uma melhor eficiência), o processo da mesma e a programação do robô, foi feito em mais ou menos 1 mês.
              Foi utilizado o software oficial da Lego para a programação do robô usando
              blocos ao estilo Scratch para a sua lógica.
              <br> <br> 2017 / 2018
          </p>
          {% load static %}
          <img src="{% static 'portfolio/images/robo.png' %}" alt="robo"
               style="margin-top: 20px">
      </div>
      <div style="text-align: center">
        <h2>
            Agriduino Project
        </h2>
          <br>
          <p>
              Agriduino Project, foi o Projecto de Aptidão Profissional (PAP)
              com o Arduino para criar uma rega automática de rabanetes.
              Foram usados sensores de luz, temperatura e humidade do solo para controlar
              os valores da plantação.
              Usei LED's para simular motores e válvulas da bomba de água e de um toldo.
              Utilizei também um módulo ESP8266 Wifi, para transmitir os dados
              recebidos pelos sensores para um site de maneira a que o dono
              consiguisse controlar a plantação à distância.
              <br> <br> 2017 / 2018
          <br>
          {% load static %}
          <img src="{% static 'portfolio/images/agriduino.png' %}" alt="agriduino"
               style="margin-top: 20px">
      </div>

      <div style="text-align: center">
        <h2>Deisi Great Game</h2>
          <br>
          <p>
              DEISI Great Game foi uma espécie de jogo da glória feito como projeto final
              da cadeira de LP2 no 2º ano - 1º Semestre.
              O projeto foi feito em Java com módulos em Kotlin (programação funcional).
              <br> <br> 2021 / 2022
          </p>
          {% load static %}
          <img src="{% static 'portfolio/images/deisiGreatGame.png' %}" alt="deisiGreatGame"
               style="margin-top: 20px;">
      </div>
    </div>

{% endblock %}

portfolio/templates/portfolio/quizz.html
{% extends 'portfolio/layout.html' %}

{% block main %}
    <fieldset class="estiloField">
        <legend>
            Quizz - PW
        </legend>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="estiloNome">
                <label for="nome">Nome:</label>
                <input type="text" id="nome" name="nome" placeholder="Nome:"><br>
            </div>

            <div class="capGlobal">
                <h3 class="tituloPergunta">
                    Pergunta Geral:
                </h3>
                <p class="pergunta">
                    1 - Que tecnologia em Programação Web é usada em Front-End development?
                </p>
                <input type="radio" id="javascript" name="p1" value="javascript">
                <label for="javascript">JavaScript</label><br>
                <input type="radio" id="html" name="p1" value="html">
                <label for="html">HTML</label><br>
                <input type="radio" id="css" name="p1" value="css">
                <label for="css">CSS</label><br>
                <input type="radio" id="django" name="p1" value="django">
                <label for="django">Django</label><br>
                <input type="radio" id="python" name="p1" value="python">
                <label for="python">Python</label><br>
            </div>

            <div class="capHTML">
                <h3 class="tituloPergunta">
                    Pergunta de HTML:
                </h3>
                <p class="pergunta">
                    2 - Que nome se dá ao conjunto das palavras seguintes em HTML? - [header, nav, main, article, section, aside, footer]
                </p>
                <input type="radio" id="elementosSemanticos" name="p2" value="Elementos_Semanticos">
                <label for="elementosSemanticos">Elementos Semânticos</label><br>
                <input type="radio" id="elementosAgrupadores" name="p2" value="Elementos_Agrupadores">
                <label for="elementosAgrupadores">Elementos Agrupadores</label><br>
                <input type="radio" id="seletoresUniversais" name="p2" value="Seletores_Universais">
                <label for="seletoresUniversais">Seletores Universais</label><br>
            </div>

            <div class="capCSS">
                <h3 class="tituloPergunta">
                    Pergunta de CSS:
                </h3>
                <p class="pergunta">
                    3 - Em CSS, "margin: Apx, Bpx, Cpx, Dpx;" em que ordem o objeto é movido?
                </p>
                <input type="radio" id="top-left-bot-right" name="p3" value="TopLeftBotRight">
                <label for="top-left-bot-right">Top(A), Left(B), Bottom(C), Right(D)</label><br>
                <input type="radio" id="top-bot-left-right" name="p3" value="TopBotLeftRight">
                <label for="top-bot-left-right">Top(A), Bottom(B), Left(C), Right(D)</label><br>
                <input type="radio" id="top-right-bot-left" name="p3" value="TopRightBotLeft">
                <label for="top-right-bot-left">Top(A), Right(B), Bottom(C), Left(D)</label><br>
            </div>

            <div class="capPython">
                <h3 class="tituloPergunta">
                    Pergunta de Python:
                </h3>
                <p class="pergunta">
                    4 - Como se define uma função em Python?
                </p>
                <input type="radio" id="createFun" name="p4" value="create_Function">
                <label for="createFun">create functionName():</label><br>
                <input type="radio" id="funFun" name="p4" value="fun_Function">
                <label for="funFun">fun functionName():</label><br>
                <input type="radio" id="defFun" name="p4" value="def_Function">
                <label for="defFun">def functioName():</label><br>
                <input type="radio" id="publicFun" name="p4" value="public_Function">
                <label for="publicFun">public [type] functionName():</label><br>
            </div>

            <div class="capDjango">
                <h3 class="tituloPergunta">
                    Pergunta de Django:
                </h3>
                <p class="pergunta">
                    5 - Em Django, qual é a rota correta para renderizar uma página HTML?
                </p>
                <input type="radio" id="confUrlViewHtml" name="p5" value="conf_url_view_html">
                <label for="confUrlViewHtml">config.urls > app.urls > app.views > página html</label><br>
                <input type="radio" id="confViewUrlHtml" name="p5" value="conf_view_url_html">
                <label for="confViewUrlHtml">config.urls > app.views > app.urls > página html</label><br>
                <input type="radio" id="viewUrlConfHtml" name="p5" value="view_url_conf_html">
                <label for="viewUrlConfHtml">app.views > app.urls > config.urls > página html</label><br>
            </div>
            <div class="btn-submit">
                <input type="submit" value="Submit"> <!-- Pôr um button com um certo verde -->
            </div>
        </form>
    </fieldset>
    <div class="grafico">
        {% load static %}
        <img src="{% static 'portfolio/images/graf.png' %}" alt="graf">
     <img src="{{pessoa.fotografia.url}}" alt="imagem">
    </div>
{% endblock %}